import { NavLink } from '@remix-run/react';
import { BASE_TOKENS, STATUS_TOKENS } from '@palettebruh/theme-toolbar';
import { TokenColorPalette } from '@palettebruh/theme-toolbar';
import {
  PageActions,
  PageHeader,
  PageHeaderDescription,
  PageHeaderHeading,
} from '~/components/PageHeader';
import { Button } from '~/components/ui/button';
import { loader as favouritesLoader } from '~/routes/_app.favourites';

export const loader = favouritesLoader;

export default function Page() {
  return (
    <>
      <PageHeader>
        <PageHeaderHeading>All your color shades</PageHeaderHeading>
        <PageHeaderDescription>
          All the CSS color tokens generated by Palettebruh, along with their{' '}
          <a href="https://www.w3.org/TR/WCAG22/">WCAG 2.2</a> and{' '}
          <a href="https://www.w3.org/TR/WCAG3/">WCAG 3.0</a> contrast grades.
        </PageHeaderDescription>
        <PageActions>
          <Button asChild size="sm">
            <NavLink to="/examples">Examples</NavLink>
          </Button>
          <Button asChild size="sm" variant="ghost">
            <NavLink to="/blocks">Browse Blocks</NavLink>
          </Button>
        </PageActions>
      </PageHeader>

      <div className="container mt-8 flex flex-col gap-y-4">
        {[...BASE_TOKENS, ...STATUS_TOKENS].map((token) => (
          <TokenColorPalette token={token} key={token} />
        ))}
      </div>
    </>
  );
}
