import type { KobayashiImage } from './types';

const ADJACENCY_MAP = {
  3: {
    'website-1': {
      default: ['0', '75', '50', '75', '0', '50', '50', '50', 0],
      'high-contrast': ['0', '85', '60', '85', '0', '50', '60', '50', 0],
      'bright-light': ['0', '45', '30', '45', '0', '0', '30', '0', 0],
      pastel: ['0', '45', '30', '45', '0', '30', '30', '30', 0],
      vibrant: ['0', '65', '45', '65', '0', '35', '45', '35', 0],
      dark: ['0', '85', '70', '85', '0', '55', '70', '55', 0],
      'hyper-color': ['0', '65', '55', '65', '0', '45', '55', '45', '0'],
    },
    'brand-2': {
      default: ['0', '75', '55', '75', '0', '0', '55', '0', '0'],
      'high-contrast': ['0', '90', '55', '90', '0', '0', '55', '0', '0'], // requires first color to be locked on white
      'bright-light': ['0', '45', '30', '45', '0', '0', '30', '0', '0'], // requires first color to be locked on white
      pastel: ['0', '45', '30', '45', '0', '0', '30', '0', '0'], // requires palette_multi
      vibrant: ['0', '55', '35', '55', '0', '0', '35', '0', '0'],
      dark: ['0', '100', '75', '100', '0', '0', '75', '0', '0'],
      'hyper-color': ['0', '75', '55', '75', '0', '0', '55', '0', '0'],
    },
    'website-magazine': {
      default: ['0', '75', '50', '75', '0', '50', '50', '50', '0'],
      'high-contrast': ['0', '85', '60', '85', '0', '50', '60', '50', '0'],
      'bright-light': ['0', '45', '30', '45', '0', '0', '30', '0', '0'],
      pastel: ['0', '45', '30', '45', '0', '30', '30', '30', '0'],
      vibrant: ['0', '65', '45', '65', '0', '35', '45', '35', '0'],
      dark: ['0', '85', '70', '85', '0', '55', '70', '55', '0'],
      'hyper-color': ['0', '65', '55', '65', '0', '45', '55', '45', '0'],
    },
    'brand-3': {
      default: ['0', '75', '55', '75', '0', '0', '55', '0', '0'],
      'high-contrast': ['0', '90', '55', '90', '0', '0', '55', '0', '0'], // requires first color to be locked on
      'bright-light': ['0', '45', '30', '45', '0', '0', '30', '0', '0'], // requires first color to be locked on white
      pastel: ['0', '45', '30', '45', '0', '0', '30', '0', '0'], // requires palette_multi
      vibrant: ['0', '55', '35', '55', '0', '0', '35', '0', '0'],
      dark: ['0', '100', '75', '100', '0', '0', '75', '0', '0'],
      'hyper-color': ['0', '75', '55', '75', '0', '0', '55', '0', '0'],
    },
  },
};

const MATERIAL_TONES = [
  0, 5, 10, 15, 20, 25, 30, 35, 40, 50, 60, 70, 80, 90, 95, 98, 99, 100,
];

const TAILWIND_TONES = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];

const BOOTSTRAP_TONES = [100, 200, 300, 400, 500, 600, 700, 800, 900];

export const KOBAYASHI_HUE_LABEL_MAP = {
  R: 'Red',
  YR: 'Yellow/Red',
  Y: 'Yellow',
  GY: 'Green/Yellow',
  G: 'Green',
  BG: 'Blue/Green',
  B: 'Blue',
  PB: 'Purple/Blue',
  P: 'Purple',
  RP: 'Red/Purple',
  N: 'Neutral',
};

export const KOBAYASHI_TONE_LABEL_MAP = {
  V: 'Vivid',
  S: 'Strong',
  B: 'Bright',
  P: 'Pale',
  Vp: 'Very Pale',
  Lgr: 'Light Grayish',
  L: 'Light',
  Gr: 'Grayish',
  Dl: 'Dull',
  Dp: 'Deep',
  Dk: 'Dark',
  Dgr: 'Dark Grayish',
};

export const KOBAYASHI_COLOR_MAP = {
  R: {
    V: '#D42934',
    S: '#D43B3F',
    B: '#DC646A',
    P: '#F1A0A6',
    Vp: '#F3B9BA',
    Lgr: '#E0B7AE',
    L: '#D3A48E',
    Gr: '#B48A7D',
    Dl: '#BF7A63',
    Dp: '#CA4336',
    Dk: '#762B22',
    Dgr: '#4F3128',
  },
  YR: {
    V: '#EC5F29',
    S: '#EA6C2A',
    B: '#ED8B39',
    P: '#F6BC98',
    Vp: '#F5CFA5',
    Lgr: '#E6CBA2',
    L: '#D9B48A',
    Gr: '#C1A087',
    Dl: '#CE9A6F',
    Dp: '#D18250',
    Dk: '#85592C',
    Dgr: '#5B4534',
  },
  Y: {
    V: '#F2C825',
    S: '#F2BC3A',
    B: '#F6CD5E',
    P: '#F8DE9C',
    Vp: '#F9E7B5',
    Lgr: '#EDE3B2',
    L: '#E2D190',
    Gr: '#D3C28A',
    Dl: '#C6AC66',
    Dp: '#C79F44',
    Dk: '#8E722A',
    Dgr: '#5E4F2D',
  },
  GY: {
    V: '#B2C43C',
    S: '#AABD4A',
    B: '#B6CB66',
    P: '#C8D7A6',
    Vp: '#D5DFB9',
    Lgr: '#C3CBA0',
    L: '#B7BD8C',
    Gr: '#8F8B6E',
    Dl: '#7D744E',
    Dp: '#697630',
    Dk: '#4D4B26',
    Dgr: '#3B3B2F',
  },
  G: {
    V: '#0C9B3C',
    S: '#1E9144',
    B: '#46A65F',
    P: '#79B68E',
    Vp: '#9BBE9D',
    Lgr: '#91AA8C',
    L: '#7FA480',
    Gr: '#627E60',
    Dl: '#556E4E',
    Dp: '#29663C',
    Dk: '#1C4226',
    Dgr: '#20422B',
  },
  BG: {
    V: '#008181',
    S: '#008080',
    B: '#3AA0A0',
    P: '#7BB5B5',
    Vp: '#9FBEBE',
    Lgr: '#9EAEAE',
    L: '#89A6A6',
    Gr: '#748B8B',
    Dl: '#5C7675',
    Dp: '#396B6A',
    Dk: '#2F4C4B',
    Dgr: '#1E3333',
  },
  B: {
    V: '#0058A2',
    S: '#00538C',
    B: '#2E6CAA',
    P: '#6D8FB3',
    Vp: '#8FA6BB',
    Lgr: '#8B9FAF',
    L: '#8095AB',
    Gr: '#767F8E',
    Dl: '#5F6F81',
    Dp: '#3E556B',
    Dk: '#2F3F52',
    Dgr: '#2A3646',
  },
  PB: {
    V: '#5032AD',
    S: '#4A3297',
    B: '#5A4CAB',
    P: '#7C74B6',
    Vp: '#A29EC0',
    Lgr: '#9A97B2',
    L: '#8E89AD',
    Gr: '#837F9D',
    Dl: '#655E8F',
    Dp: '#55406E',
    Dk: '#40315C',
    Dgr: '#332C47',
  },
  P: {
    V: '#8C3EAA',
    S: '#7C378F',
    B: '#9063B5',
    P: '#A28AC1',
    Vp: '#BAAACF',
    Lgr: '#B29DB8',
    L: '#A988B8',
    Gr: '#9C859B',
    Dl: '#876181',
    Dp: '#6D375F',
    Dk: '#522E4F',
    Dgr: '#442C42',
  },
  RP: {
    V: '#A52D72',
    S: '#9C356B',
    B: '#AD4C7F',
    P: '#C67397',
    Vp: '#CDA3B9',
    Lgr: '#B999A6',
    L: '#A97E92',
    Gr: '#9B7C82',
    Dl: '#895D5F',
    Dp: '#7F3F40',
    Dk: '#5F2E34',
    Dgr: '#4D2D33',
  },
  N: {
    '9.5': '#ECECEC',
    9: '#DDDDDD',
    8: '#CCCCCC',
    7: '#B3B3B3',
    6: '#959595',
    5: '#7F7F7F',
    4: '#666666',
    3: '#4D4D4D',
    2: '#333333',
    '1.5': '#1D1D1D',
  },
};

export const KOBAYASHI_LIFESTYLE_KEYWORDS = {
  pretty: ['sweet', 'pretty', 'cute', 'childlike'],
  casual: [
    'cheerful',
    'happy',
    'festive',
    'enjoyable',
    'bright',
    'dazzling',
    'merry',
    'amusing',
    'casual',
    'flamboyant',
    'colorful',
    'showy',
    'vivid',
    'tropical',
  ],
  romantic: [
    'sweet',
    'charming',
    'amiable',
    'innocent',
    'agreeable to the touch',
    'supple',
    'dreamy',
    'sweet and dreamy',
    'soft',
    'romantic',
  ],
  natural: [
    'sunny',
    'gentle',
    'intimate',
    'generous',
    'pleasant',
    'lighthearted',
    'restful',
    'free',
    'healthy',
    'tender',
    'cultured',
    'delicate',
    'natural',
    'citrus',
    'plain',
    'tranquil',
    'wholesome',
    'peaceful',
    'sweet-sour',
    'feminine',
    'fresh',
    'simple and appealing',
    'domestic',
    'emotional',
    'dry',
    'open',
    'mild',
    'gentle and elegant',
    'delicious',
    'nostalgic',
  ],
  clear: [
    'light',
    'neat',
    'fresh and young',
    'clear',
    'pure',
    'pure and simple',
    'clean',
    'crystalline',
    'refreshing',
    'clean and fresh',
    'simple',
  ],
  'cool-casual': [
    'youthful',
    'steady',
    'young',
    'sporty',
    'agile',
    'smart',
    'speedy',
    'western',
  ],
  chich: [
    'quiet',
    'chic',
    'noble and elegant',
    'Japanese',
    'simple',
    'quiet',
    'sober and elegant',
    'stylish',
  ],
  modern: [
    'urban',
    'composed',
    'progressive',
    'distinguished',
    'intellectual',
    'modern',
    'cultivated',
    'precise',
    'exact',
    'sharp',
    'rational',
    'masculine',
    'earnest',
    'sublime',
    'proper',
    'metallic',
  ],
  elegant: [
    'feminine',
    'tender',
    'cultured',
    'delicate',
    'natural',
    'simple and appealing',
    'emotional',
    'dry',
    'sleek',
    'pure and elegant',
    'elegant',
    'polished',
    'sedate',
    'graceful',
    'noble',
    'fashionable',
    'refined',
    'subtle',
    'calm',
    'interesting',
    'mysterious',
    'modest',
    'brilliant',
  ],
  dynamic: [
    'dynamic',
    'lively',
    'hot',
    'provocative',
    'vigorous',
    'forceful',
    'bold',
    'active',
    'intense',
    'fiery',
    'striking',
  ],
  ethnic: ['ethnic', 'wild', 'robust', 'untamed'],
  gorgeous: [
    'gorgeous',
    'flamboyant',
    'abundant',
    'rich',
    'substantial',
    'glossy',
    'aromatic',
    'mature',
    'extravagant',
    'brilliant',
    'fascinating',
    'gorgeous',
    'luxurious',
    'decorative',
    'mellow',
  ],
  classic: [
    'classic',
    'provincial',
    'rustic',
    'tasteful',
    'complex',
    'old-fashioned',
    'traditional',
    'conservative',
    'mellow',
    'elaborate',
    'heavy and deep',
    'sturdy',
  ],
  dandy: [
    'diligent',
    'subtle and mysterious',
    'quiet and sophisticated',
    'eminent',
    'bitter',
    'placid',
    'aristocratic',
    'dapper',
    'precious',
    'formal',
    'solemn',
    'majestic',
    'dignified',
    'practical',
    'heavy and deep',
    'sound',
    'majestic',
    'strong and robust',
    'serious',
  ],
  formal: [
    'formal',
    'precious',
    'solemn',
    'majestic',
    'dignified',
    'sublime',
    'earnest',
    'proper',
  ],
} satisfies Record<KobayashiImage, string[]>;

export const KOBAYASHI_COLOR_COMBINATIONS_MAP = {
  pretty: {
    pretty: [
      ['Y/P', 'R/P', 'YR/Vp'],
      ['Y/B', 'RP/B', 'BG/B'],
      ['R/P', 'Y/P', 'BG/B'],
      ['RP/P', 'Y/Vp', 'BG/Lgr'],
      ['RP/B', 'Y/Vp', 'PB/B'],
      ['RP/P', 'N9.5', 'Y/P'],
    ],
    cute: [
      ['R/P', 'Y/P', 'B/P'],
      ['RP/B', 'Y/P', 'G/P'],
      ['RP/B', 'Y/Vp', 'GY/B'],
      ['R/B', 'Y/P', 'G/P'],
      ['R/P', 'Y/P', 'B/P'],
      ['RP/B', 'Y/P', 'BG/B'],
    ],
  },
  casual: {
    cheerful: [
      ['R/B', 'YR/P', 'Y/P'],
      ['R/B', 'YR/P', 'Y/P'],
      ['R/B', 'Y/B', 'R/P'],
      ['YR/P', 'R/B', 'Y/P'],
    ],
    enjoyable: [
      ['YR/V', 'Y/V', 'B/B'],
      ['YR/S', 'Y/B', 'BG/B'],
      ['R/B', 'Y/B', 'R/P'],
      ['YR/V', 'Y/V', 'GY/V'],
      ['R/B', 'Y/P', 'G/B'],
      ['YR/S', 'Y/V', 'BG/B'],
      ['RP/B', 'B/B', 'Y/B'],
      ['GY/P', 'RP/B', 'PB/S'],
    ],
    friendly: [
      ['YR/B', 'N9.5', 'Y/B'],
      ['YR/P', 'Y/Vp', 'GY/B'],
      ['YR/P', 'Y/Vp', 'Y/B'],
      ['YR/L', 'Y/Lgr', 'BG/Lgr'],
      ['YR/P', 'Y/Vp', 'GY/B'],
      ['YR/L', 'BG/Dp', 'Y/L'],
    ],
  },
  dynamic: {
    hot: [
      [],
    ],
  },
  gorgeous: {
    abundant: [['']],
    decorative: [['']],
    mature: [['']],
  },
  ethnic: {
    default: [['']],
  },
  romantic: {
    default: [['']],
  },
  natural: {
    free: [
      ['YR/P', 'Y/Vp', 'BG/P'],
      ['YR/P', 'Y/Vp', 'GY/P'],
      ['GY/B', 'Y/Vp', 'BG/P'],
      ['YR/L', 'Y/Vp', 'GY/P'],
      ['GY/P', 'Y/Vp', 'G/P'],
    ],
    fresh: [
      ['GY/V', 'N9.5', 'G/Vp'],
      ['GY/B', 'N9.5', 'PB/B'],
      ['GY/P', 'BG/B', 'B/Vp'],
      ['G/S', 'Y/Vp', 'G/P'],
      ['Y/Vp', 'GY/P', 'G/B'],
      ['G/S', 'Y/Vp', 'G/P'],
      ['GY/V', 'N9.5', 'G/Vp'],
      ['GY/P', 'GY/Vp', 'G/L'],
      ['GY/Lgr', 'N9.5', 'BG/L'],
      ['GY/B', 'N9.5', 'B/B'],
      ['GY/B', 'N9.5', 'PB/B'],
    ],
    generous: [
      ['R/L', 'R/P', 'Y/Vp'],
      ['R/L', 'YR/Lgr', 'YR/DI'],
      ['YR/Lgr', 'R/L', 'YR/DI'],
      ['YR/L', 'Y/Vp', 'Y/L'],
      ['R/L', 'R/P', 'Y/Vp'],
      ['YR/Lgr', 'Y/Vp', 'GY/L'],
    ],
    healthy: [
      ['YR/B', 'Y/Vp', 'B/B'],
      ['YR/B', 'N9.5', 'Y/P'],
      ['Y/V', 'N9.5', 'GY/V'],
      ['YR/P', 'YR/Vp', 'GY/P'],
      ['YR/L', 'Y/Vp', 'G/L'],
      ['Y/P', 'Y/Vp', 'BG/P'],
    ],
    natural: [
      ['YR/L', 'Y/L', 'Y/Lgr'],
      ['Y/L', 'Y/Lgr', 'GY/L'],
      ['Y/L', 'GY/Lgr', 'GY/L'],
      ['YR/DI', 'YR/Lgr', 'GY/S'],
      ['GY/Vp', 'GY/L', 'GY/Dp'],
      ['GY/Lgr', 'Y/Vp', 'G/Lgr'],
      ['GY/Gr', 'Y/L', 'G/DI'],
      ['Y/Lgr', 'G/Gr', 'G/Dp'],
    ],
    peaceful: [
      ['B/L', 'Y/Vp', 'G/Lgr'],
      ['YR/L', 'YR/Vp', 'GY/L'],
      ['G/Lgr', 'BG/Gr', 'N7'],
      ['YR/Vp', 'N8', 'G/L'],
      ['G/Gr', 'Y/Lgr', 'N6'],
      ['YR/Lgr', 'Y/Vp', 'BG/Lgr'],
      ['YR/P', 'Y/Vp', 'B/P'],
      ['G/Lgr', 'Y/Vp', 'B/L'],
    ],
    restful: [
      ['YR/P', 'Y/Vp', 'GY/Lgr'],
      ['YR/P', 'YR/Vp', 'Y/Lgr'],
      ['YR/S', 'Y/Lgr', 'Y/L'],
      ['YR/Vp', 'YR/P', 'GY/Lgr'],
      ['Y/Vp', 'GY/Lgr', 'GY/L'],
    ],
    'simple-and-appealing': [
      ['Y/Lgr', 'GY/L', 'GY/Gr'],
      ['Y/L', 'Y/Vp', 'N8'],
      ['GY/Gr', 'Y/Lgr', 'N6'],
      ['Y/Lgr', 'G/Lgr', 'N7'],
      ['Y/L', 'Y/Gr', 'N7'],
      ['GY/Gr', 'Y/Lgr', 'N6'],
    ],
    wholesome: [
      ['YR/L', 'Y/Vp', 'GY/Lgr'],
      ['Y/L', 'Y/Vp', 'GY/Lgr'],
      ['YR/L', 'Y/Vp', 'Y/L'],
      ['Y/L', 'N9.5', 'GY/S'],
      ['Y/Lgr', 'N9', 'GY/L'],
    ],
  },
  clear: {
    default: [['']],
  },
  'cool-casual': {
    default: [['']],
  },
  modern: {
    default: [['']],
  },
  elegant: {
    default: [['']],
  },
  dandy: {
    default: [['']],
  },
  formal: {
    default: [['']],
  },
  chich: {
    default: [['']],
  },
  classic: {
    default: [['']],
  },
} satisfies Record<KobayashiImage, Record<string, string[][]>>;

export { ADJACENCY_MAP, MATERIAL_TONES, TAILWIND_TONES, BOOTSTRAP_TONES };
